services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - marry_me_kafka

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "hello-world-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka-manager
    networks:
      - marry_me_kafka

  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_CREATE_TOPICS: "hello-world-topic:1:1, hello-world-topic-2:1:1"
    depends_on:
      - zookeeper
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
